sidebar:
  menu:
    post: '[btn.blog](/)'
    more: '[æ›´å¤š](/more/)'
  # Sidebar widgets
  widgets:
    # Recent update
    recent:
      layout: recent
      rss: /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
    # welcome
    welcome:
      layout: markdown
      title: About me
      content: |
        ğŸ˜‰ Ciao~ è¿™é‡Œæ˜¯ [zennlyu](https://github.com/zennlyu) çš„ä¸ªäººå°ç«™ ğŸ˜‰
        ï½ æ”¿åºœåœ¨å†Œç¯ä¿ä¹‰å·¥ï¼Œé•¿æœŸæ´»è·ƒå¹¶æ¢ç´¢ç¯å¢ƒé—®é¢˜çš„è§„æ¨¡åŒ–æŠ€æœ¯è§£å†³æ–¹æ¡ˆ(like [Ocean Cleanup](https://theoceancleanup.com/)) ğŸŒŠ
        ï½ å†…å®¹ä»¥æŠ€æœ¯ç§¯ç´¯ä¸ºä¸»ï¼Œä¹Ÿä¸æ’é™¤å¼€è¾Ÿäº›è®¸ç”Ÿæ´»ä¸å®¡ç¾çš„ç©ºé—´ ğŸŒ¹
        ï½ æ¬¢è¿é€šè¿‡ [twitter](https://twitter.com/zennryu616) æˆ–è€… [telegram](https://t.me/s081z) è”ç³»æˆ‘ ğŸ¥³
        ğŸ“®ï¼š[zennlyu@gmail.com](zennlyu@gmail.com)